name: Update Package Version

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package.json
        run: |
          node ./scripts/update-version.js ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit changes
        run: |
          git config user.name "Cenkaifeng"
          git config user.email "cenkaifeng@ones.com"
          git add package.json
          git commit -m "Update version to ${{ env.VERSION }} for release ${{ github.ref }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
